---
name: Test-SFTP
version: 1.05
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
abstract: An object to help test SFTPs
license: perl
build_requires:
  English: 1.02
  Term::ReadLine: 0
  Term::ReadPassword: 0
  Test::More: 0
requires:
  Carp: 0
  Moose: 0.63
  Net::SFTP::Foreign: 0
  Test::Builder: 0
  namespace::autoclean: 0
  parent: 0
  perl: 5.006
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Test::SFTP:
    file: lib/Test/SFTP.pm
    version: 1.05
resources:
  license: http://dev.perl.org/licenses/
